name: release CI

on:
  push:
    tags: v*.*.*    

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: tirpidz/lovely:${{steps.vars.outputs.tag}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
